---
title: "Covid91 vaccine study Final2024"
author: "Mairani G"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="finalSumr2024.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

## Males
$H_0$: The Covid921 Vaccine is not effective in males.

$H_A$: The Covid921 vaccine is effective in males.

### Methods

### Descriptive Results

### Graphical Results 

### Numerical

### Inferential Results

## Females

$H_0$: The Covid921 Vaccine is not effective in females.

$H_A$: The Covid921 vaccine is effective in females.

### Methods

### Descriptive Results

### Graphical Results 

## LGBTQ
$H_0$: The Covid921 Vaccine is not effective on the LGBTQ community.

$H_A$: The Covid921 vaccine is effective on the LGBTQ community


## Drug Users

$H_0$: The Covid921 Vaccine is not effective on drug users.   

$H_A$: The Covid921 vaccine is effective on drug users.  


### Methods

### Descriptive results

#### Graphical results 

#### Numerical

#### Inferential results

#### Conclusion


# Overall Results and Conclusions